### ISSUE TITLE
リンク切れ他

### ISSUE THREAD

**Issue by yutopia** [skk-dev/temp_web#6]
ファイル名の変更および、mainの下がGitHubに移行したことによるリンク切れがいくつか生じているようです。
一部を確認できただけなのですが、主にドキュメントからmainのファイルを呼んでいる箇所などで古いファイルを呼んでいたりデッドリンクになっていたりするものがあるようです。
web/maint_progs/cvswork.sh などを見ると、texi2html  で変換する元のファイルが /circus/openlab/skk/skk/main/doc/skk.texi を nkf で euc コードに変換したもののようです。
  もっとも CVS trunk html (フレーム版)  となっていますね。
GitHub から直接持ってくる方法があればよいのですが。

**Comment by tkita** [comment]
openlab 側で wget 実行すれば取得できるようです。
```
[USER@local ~]$ ssh USER@openlab.jp
  :
Welcome to FreeBSD!
  :
[USER@openlab ~]$ wget --no-check-certificate https://raw.github.com/skk-dev/ddskk/master/doc/skk.texi
  :
2015-01-17 12:16:29 (2.13 MB/s) - 'skk.texi' saved [394511/394511]
[USER@openlab ~]$ ls -l
-rw-r--r--  1 USER  openlab     394511 Jan 17 12:16 skk.texi
[USER@openlab ~]$ exit
[USER@local ~]$
```

**Comment by yutopia** [comment]
了解しました。ありがとうございます。
すると、こんな感じになるんでしょうか？
```
--- cvswork.sh	2003-11-09 16:34:29.000000000 +0900
+++ cvswork.sh_new	2015-01-17 22:55:55.941823200 +0900
@@ -12,10 +12,11 @@
 /bin/cp -f /circus/openlab/skk/skk/web/*.html.in /circus/openlab/skk; \
 cd /circus/openlab/skk/ && \
 for i in *.html.in ; do newname=$(basename $i .in); mv -f $i $newname; done; \
-/usr/local/bin/nkf -e /circus/openlab/skk/skk/main/doc/skk.texi > $HOME/tmp/skk-manual-ja.texi;\
 cd $HOME/tmp && \
+wget --no-check-certificate https://raw.github.com/skk-dev/ddskk/master/doc/skk.texi;\
+/usr/local/bin/nkf -e skk.texi > $HOME/tmp/skk-manual-ja.texi;\
 $HOME/bin/texi2html -frame -split=chapter $HOME/tmp/skk-manual-ja.texi;\
 /bin/mv -f $HOME/tmp/*.html /circus/openlab/skk/skk-manual;\
-rm -f $HOME/tmp/skk-manual-ja.texi
+rm -f $HOME/tmp/skk-manual-ja.texi $HOME/tmp/skk.texi
 #find . -exec chown www /circus/openlab/skk/log/*.log /usr/sbin/chown  {} \;
 # end of cvswork.sh
```
texi2html  も nkf  も手元にないものでテストできないのですが。

**Comment by tkita** [comment]
試してみたところ上手くいったようなので、 cvs commit しました。
次回の反映でチェックしてみてください。

**Comment by yutopia** [comment]
わかりました。

**Comment by yutopia** [comment]
最新版が反映されていることを確認しました。

が、 たまたまみつけたのですが http://openlab.ring.gr.jp/skk/skk-manual/skk-manual-ja_10.html#SEC223 などで文字化けがありました。(Firefox で確認) 
EUC-JP を指定することで表示はできますが、一部に表示できない文字があるようです。
索引のところの表示が崩れてるみたいです。これは texi2html の仕様なんでしょうか。

あと、わからないのは、 SKKの作者のところの私のメールアドレスが古いままになっているんですよ。

なんかまだ色々とまざっているのかもしれません。

**Comment by tkita** [comment]
nkf を iconv に変えてみたり色々実験しましたが、結局、
cvs に置かれたままの skk.texi (iso-2022-jp-3) を nkf -e して texi2html してみたところ、おおむらさんと同じ結果になりました。したがって、もともと文字化けしてたってオチだったりするような気がします。

「事後処理で sed で charset を突っ込む」を思いつきましたので、これは明日にでも。

**Comment by yutopia** [comment]
あいたた。
了解しました。

**Comment by tkita** [comment]
このパッチでイケそうなのですが、どう思われますか？
utf-8 のままページを公開するものです。
```diff
Index: maint_progs/cvswork.sh
===================================================================
RCS file: /circus/cvsroot/skk/web/maint_progs/cvswork.sh,v
retrieving revision 1.8
diff -u -r1.8 cvswork.sh
--- maint_progs/cvswork.sh	17 Jan 2015 15:11:03 -0000	1.8
+++ maint_progs/cvswork.sh	21 Jan 2015 04:47:55 -0000
@@ -14,9 +14,11 @@
 for i in *.html.in ; do newname=$(basename $i .in); mv -f $i $newname; done; \
 cd $HOME/tmp && \
 wget --no-check-certificate https://raw.github.com/skk-dev/ddskk/master/doc/skk.texi;\
-/usr/local/bin/nkf -e skk.texi > $HOME/tmp/skk-manual-ja.texi;\
+/bin/mv skk.texi > $HOME/tmp/skk-manual-ja.texi;\
 $HOME/bin/texi2html -frame -split=chapter $HOME/tmp/skk-manual-ja.texi;\
-/bin/mv -f $HOME/tmp/*.html /circus/openlab/skk/skk-manual;\
-rm -f $HOME/tmp/skk-manual-ja.texi $HOME/tmp/skk.texi
+/bin/rm -f /circus/openlab/skk/skk-manual;\
+for f in *.html ; do sed -e 's/texi2html 1.65">/texi2html 1.65">\
+<META http-equiv="Content-Type" content="text\/html; charset=utf-8">/g' $f > /circus/openlab/skk/skk-manual/$f ; done
+rm -f $HOME/tmp/skk-manual-ja.texi
 #find . -exec chown www /circus/openlab/skk/log/*.log /usr/sbin/chown  {} \;
 # end of cvswork.sh
```
ただし、それでもページ中の一部文字は化けたままです。
手元の texi2html 5.0 だと、自動的に charset が付され、文字も正しく表示されることから、
openlab.jp のホームディレクトリに 5.0 をインストールしたいのだけれど、FreeBSD  の基本を知らないもので．．．

**Comment by tkita** [comment]
> あと、わからないのは、 SKKの作者のところの私のメールアドレスが古いままになっているんですよ。

テストで生成した charset utf-8 版を公開領域に mv しました。 ocn から dion に変わっていることをご確認ください。
次回で ocn に戻ったならば、どこかに間違いが潜んでいますね。

**Comment by yutopia** [comment]
ちょっと、
> +/bin/mv skk.texi > $HOME/tmp/skk-manual-ja.texi;\
が動いているのが解せないのですが。
> +/bin/mv skk.texi   $HOME/tmp/skk-manual-ja.texi;\
では？

openlab は FreeBSD だったのですね。
普通は package か ports を使いますけど、ホームに置くならあまり気にしなくてもいいのでは。
```
$ cd
$ tar xjvf texi2html-5.0.tar.bz2
$ cd texi2html-5.0
$ ./configure --prefix=$HOME
$ make
$ make install
```
でいけると思います。
texi2html に渡すオプションはうまくやらないとおかしなものができるようですが。
;; 手元の cygwin でやってみたのですが、目次が最後に来てしまいました。
というか、texi2html は perl script だったのですね。

> テストで生成した charset utf-8 版を公開領域に mv しました。 ocn から dion に変わっていることをご確認ください。

確認しました。ありがとうございます。
